### PR TITLE
enhance tests

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by jthill** [comment]
I don't see what behavior the added output is meant to illustrate, can you explain?

**Comment by rubo77** [comment]
On my large screen, I had no effect by such a small list, It all fitted in one row, so I needed some more items, and also this shows more, how the sorting outoput is mean (columns instead of rows) also the echo shows the command used for that output.

ANd I called chmod +x on the test file

**Comment by jthill** [comment]
When I merged your self-doc I also fixed the column-width propagation, it was somehow resetting `COLUMNS` so I changed the name and it went back to doing what I thought it was doing all along. Try the original tests with the new code.

**Comment by jthill** [comment]
I believe this pr was mooted by the merge of pr6, which I amended to also correct `$COLUMNS` resetting by surprise.

**Pull request closed without merging**
